2.5
Make include to make GE compile.

Py 2.3 doesnt compile expressions/Value.cpp btw... 
Value.cpp:616: error: 'class PyObjectPlus' has no member named 'ob_type'

Probably need to wait for py 3.1 :)